
name: Hello World
on:
  push:

jobs:
  hello-job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Echo text
        run: echo "Hello, world!"
